leaderboard api
EvgeshaI/memory-cards pull request #28
Opened 2024-09-25 16:26 UTC by EvgeshaI

### Подключит API для лидерборда

<img width="766" alt="Снимок экрана 2024-09-25 в 15 33 32" src="https://github.com/user-attachments/assets/2593d019-1290-44ee-b1ff-98f317766bde">

2024-09-28 12:07 UTC, EvgeshaI commented on packages/client/src/widgets/leaderboard/ui/LeadersList.tsx
> +  const filteredAndSortedPlayers = [...leaders].sort(
не, sort модифицирует исходный массив, ошибки будут

2024-09-28 19:00 UTC, kyzinatra commented on packages/client/src/entities/game/api/leaderboardApi.ts
> +    credentials: 'include',
Можно лучше: эта часть повторяется в каждом запросе. Стоит вынести обертку над `fetch` в отдельную функцию

2024-09-28 19:01 UTC, kyzinatra commented on packages/client/src/entities/game/api/leaderboardApi.ts
> +  }
Проверку тоже лучше вынести в эту функцию, чтобы не повторять

2024-09-28 19:01 UTC, kyzinatra commented on packages/client/src/entities/game/lib/mapLeaders.ts
> +  data.map((entry) => ({
Надо исправить: стоит типизировать `data`

2024-09-28 19:05 UTC, kyzinatra requested changes
Отличная работа! Мне понравилась реализация запросов. 

Едиственное что хотел спросить проверяли ли вы работу этой логики

```js


 try {
      await dispatch(fetchNewLeader(time));
      dispatch(gameActions.saveGameTime(time));
      navigate(routePaths[RouteNames.END_GAME]);
    } catch (error) {
      notifications.show({
        title: 'error',
        message: 'Ошибка при отправке лидера на сервер'
      })
    }

```

Мне кажется, что `await dispatch(fetchNewLeader(time));` не вернет ошибку даже если вы ее пробрасываете в `createAsyncThunk` так как `createAsyncThunk` поймает ее и конвертирует в соответствующее событие `fetchNewLeader.rejected` а не в ошибку.

Также стоит типизировать `data: any`. Также рекомендую вынести в отдельную обертку `fetch` с его базовыми настройками

2024-10-05 08:07 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-10-05 11:02 UTC, merged